version: "3"

services:
  app:
    build: .
    container_name: app
    command: gunicorn --bind 0.0.0.0:5000 run:app
    ports:
      - 5000:5000
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always
  db:
    env_file:
      - .env.prod
    image: postgres:12-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data:
